run:
  timeout: 5m
  go: "1.25"
  tests: true
  skip-dirs-use-default: true
  skip-dirs:
    - submodules

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
